CREATE TABLE COUNTRY(
	CNAME VARCHAR(100),
	PRIMARY KEY (CNAME)
);

CREATE TABLE SQUADS(
	CNAME VARCHAR(100),
	PLAYERNAME VARCHAR(100),
	PLAYERNUMBER INT,
	PRIMARY KEY (CNAME,PLAYERNAME, PLAYERNUMBER),
	FOREIGN KEY (CNAME) REFERENCES COUNTRY(CNAME)
);	

CREATE TABLE STADIUM (
	SNAME VARCHAR(100),
	CAPACITY INT,
	HISTORY TEXT,
	LAT DECIMAL(9,6),
	LNG DECIMAL(9,6),
	RNAME VARCHAR(100),
	COUNTRY VARCHAR(100),
	PRIMARY KEY (LAT, LNG)
	
);
SHOW ENGINE INNODB STATUS;

CREATE TABLE WCDATE(
	WCYEAR INT,
	WCMONTH INT,
	WCDAY INT,
	PRIMARY KEY (WCDAY,WCMONTH,WCYEAR)
);
